### PR TITLE
Fix possible concurrent init in Toolbox and improve performance

### PR DESCRIPTION
**Pull request by yongce**

### CODE REVIEW

**Comment by preedee136** [comment]
🙌🙌🙌

**Comment by Chainfire** [comment]
Why is init() changed from public to private? This prevents the library user from running the init command when convenient. init() requires to be run from a background thread, while command() doesn't (unless it call init).

**Comment by yongce** [comment]
done

**Comment by ttimz1313** [comment]
Y

**Comment by Chainfire** [comment]
Shouldn't the output of toybox be split on whitespace before being added to the hash?

AFAIK, toybox's output is:

applet01 applet02 applet03 applet04
applet05 applet06 applet07 applet08
applet09 applet10 applet11 applet12
applet13 applet14 applet15 applet16

Rather than:

applet01
applet02
applet03
...

that this pull request seems to expect.

**Comment by n054** [comment]
@Chainfire, I'm going to run these through my device.

**Comment by atcharatip** [comment]
#65 @

- [ ] 

- 1.

**Comment by fixmeright** [comment]
ol

**Comment by fixmeright** [comment]
sremd pk9

**Pull request closed without merging**
