### PR TITLE
Added basic support for sepolicy-inject

### PR DESCRIPTION
**Pull request by pylerSM**

### CODE REVIEW

**Comment by Chainfire** [comment]
While I am not an expert on sepolicy-inject use, it seems to me your command conversion routine will fail for every single one the policies I use in my own apps.

**Comment by pylerSM** [comment]
Conversion worked for simple, not with brackets commands

**Comment by Chainfire** [comment]
Yeah, you'd need to unwind the brackets I guess. supolicy does this internally. I'm not against support for sepolicy-inject, but I'm wary adding a commit that implies policies will work when they will not.

**Comment by pylerSM** [comment]
it even work for allow sdcardd unlabeled dir getattr read write ... I tried to spent some time to parse multiple brackets but it was.. still something wrong.

I feel well with this since, since if conversion error, nothing is executed and haveInjected is false.

**Pull request closed without merging**
